create table cart (id bigint generated by default as identity, total decimal(19,2), primary key (id))
create table cart_items (cart_id bigint not null, items_id bigint not null)
create table item (id bigint generated by default as identity, description varchar(255) not null, name varchar(255) not null, price decimal(19,2) not null, primary key (id))
create table user (id bigint generated by default as identity, password varchar(255) not null, username varchar(255) not null, cart_id bigint, primary key (id))
create table user_order (id bigint generated by default as identity, total decimal(19,2), user_id bigint not null, primary key (id))
create table user_order_items (user_order_id bigint not null, items_id bigint not null)
alter table user drop constraint if exists UK_sb8bbouer5wak8vyiiy4pf2bx
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table cart_items add constraint FKbgmrxyvqs3kxt1im75fde3psy foreign key (items_id) references item
alter table cart_items add constraint FK99e0am9jpriwxcm6is7xfedy3 foreign key (cart_id) references cart
alter table user add constraint FKtqa69bib34k2c0jhe7afqsao6 foreign key (cart_id) references cart
alter table user_order add constraint FKj86u1x7csa8yd68ql2y1ibrou foreign key (user_id) references user
alter table user_order_items add constraint FKghpu6f1jrpho0deyeltq47u2u foreign key (items_id) references item
alter table user_order_items add constraint FKt6k533isn84ef898d6sln1xna foreign key (user_order_id) references user_order